print("Salom")
print('Yangi qator')
print("Yangi yangi qatot")
print("Yana yangi qatot")
print("Yana yangi qatot")
print("Yana yangi qatot")
print("Yana yangi qatot")
print("Yana yangi qatot")
print("Yana yangi qatot")
print("Yana yangi qatot")
